[pytest]
DJANGO_SETTINGS_MODULE = movie_picker.settings
markers =
    slow: тесты, которые долго выполняются
    views: тесты представлений
    models: тесты моделей
    forms: тесты форм
    integration: интеграционные тесты
    recommendations: тесты системы рекомендаций